# AUTO-GENERATED by CANbus_data/tools/gen_ha_bootstrap.py -- do not edit by hand.
# Regenerate after changing EZ_SENSORS / BG_SENSORS.
#
# Home Assistant python_script (runs in the restricted python_script sandbox).
# Creates each CAN sensor as "unavailable" if it does not already exist, so the
# dashboard shows the entity (not "entity not found") and history stays
# browsable before the CAN reader add-on has live data. Triggered on the
# homeassistant.start event by the automation in packages/canbus_bootstrap.yaml.
# The existence check means it never clobbers a live value the add-on pushed.

SENSORS = [
    {"id": 'sensor.ezkontrol_bus_voltage', "name": 'EZkontrol Bus Voltage', "unit": 'V', "dclass": 'voltage', "icon": 'mdi:flash'},
    {"id": 'sensor.ezkontrol_bus_current', "name": 'EZkontrol Bus Current', "unit": 'A', "dclass": 'current', "icon": 'mdi:current-dc'},
    {"id": 'sensor.ezkontrol_phase_current', "name": 'EZkontrol Phase Current', "unit": 'A', "dclass": 'current', "icon": 'mdi:current-ac'},
    {"id": 'sensor.ezkontrol_motor_speed', "name": 'EZkontrol Motor Speed', "unit": 'rpm', "dclass": None, "icon": 'mdi:speedometer'},
    {"id": 'sensor.ezkontrol_controller_temp', "name": 'EZkontrol Controller Temp', "unit": '°C', "dclass": 'temperature', "icon": 'mdi:thermometer'},
    {"id": 'sensor.ezkontrol_motor_temp', "name": 'EZkontrol Motor Temp', "unit": '°C', "dclass": 'temperature', "icon": 'mdi:thermometer-alert'},
    {"id": 'sensor.ezkontrol_throttle', "name": 'EZkontrol Throttle', "unit": '%', "dclass": None, "icon": 'mdi:gauge'},
    {"id": 'sensor.ezkontrol_gear', "name": 'EZkontrol Gear', "unit": None, "dclass": None, "icon": 'mdi:car-shift-pattern'},
    {"id": 'sensor.ezkontrol_brake', "name": 'EZkontrol Brake', "unit": None, "dclass": None, "icon": 'mdi:car-brake-alert'},
    {"id": 'sensor.ezkontrol_op_mode', "name": 'EZkontrol Op Mode', "unit": None, "dclass": None, "icon": 'mdi:cog'},
    {"id": 'sensor.ezkontrol_dc_contactor', "name": 'EZkontrol Dc Contactor', "unit": None, "dclass": None, "icon": 'mdi:electric-switch'},
    {"id": 'sensor.ezkontrol_errors', "name": 'EZkontrol Errors', "unit": None, "dclass": None, "icon": 'mdi:alert-circle'},
    {"id": 'sensor.ezkontrol_error_count', "name": 'EZkontrol Error Count', "unit": None, "dclass": None, "icon": 'mdi:counter'},
    {"id": 'sensor.bestgo_soc', "name": 'BESTGO Soc', "unit": '%', "dclass": 'battery', "icon": 'mdi:battery-50'},
    {"id": 'sensor.bestgo_soh', "name": 'BESTGO Soh', "unit": '%', "dclass": None, "icon": 'mdi:battery-heart'},
    {"id": 'sensor.bestgo_pack_voltage', "name": 'BESTGO Pack Voltage', "unit": 'V', "dclass": 'voltage', "icon": 'mdi:flash'},
    {"id": 'sensor.bestgo_pack_current', "name": 'BESTGO Pack Current', "unit": 'A', "dclass": 'current', "icon": 'mdi:current-dc'},
    {"id": 'sensor.bestgo_pack_temp', "name": 'BESTGO Pack Temp', "unit": '°C', "dclass": 'temperature', "icon": 'mdi:thermometer'},
    {"id": 'sensor.bestgo_cell_voltage_min', "name": 'BESTGO Cell Voltage Min', "unit": 'mV', "dclass": 'voltage', "icon": 'mdi:battery-low'},
    {"id": 'sensor.bestgo_cell_voltage_max', "name": 'BESTGO Cell Voltage Max', "unit": 'mV', "dclass": 'voltage', "icon": 'mdi:battery-high'},
    {"id": 'sensor.bestgo_cell_voltage_delta', "name": 'BESTGO Cell Voltage Delta', "unit": 'mV', "dclass": None, "icon": 'mdi:delta'},
    {"id": 'sensor.bestgo_cell_temp_min', "name": 'BESTGO Cell Temp Min', "unit": '°C', "dclass": 'temperature', "icon": 'mdi:thermometer-low'},
    {"id": 'sensor.bestgo_cell_temp_max', "name": 'BESTGO Cell Temp Max', "unit": '°C', "dclass": 'temperature', "icon": 'mdi:thermometer-high'},
    {"id": 'sensor.bestgo_charge_voltage_limit', "name": 'BESTGO Charge Voltage Limit', "unit": 'V', "dclass": 'voltage', "icon": 'mdi:battery-charging'},
    {"id": 'sensor.bestgo_charge_current_limit', "name": 'BESTGO Charge Current Limit', "unit": 'A', "dclass": 'current', "icon": 'mdi:current-dc'},
    {"id": 'sensor.bestgo_discharge_current_limit', "name": 'BESTGO Discharge Current Limit', "unit": 'A', "dclass": 'current', "icon": 'mdi:current-dc'},
    {"id": 'sensor.bestgo_discharge_voltage_limit', "name": 'BESTGO Discharge Voltage Limit', "unit": 'V', "dclass": 'voltage', "icon": 'mdi:battery-arrow-down'},
    {"id": 'sensor.bestgo_alarms', "name": 'BESTGO Alarms', "unit": None, "dclass": None, "icon": 'mdi:alert-circle'},
    {"id": 'sensor.bestgo_warnings', "name": 'BESTGO Warnings', "unit": None, "dclass": None, "icon": 'mdi:alert'},
    {"id": 'sensor.bestgo_firmware', "name": 'BESTGO Firmware', "unit": None, "dclass": None, "icon": 'mdi:chip'},
    {"id": 'sensor.bestgo_nominal_capacity', "name": 'BESTGO Nominal Capacity', "unit": 'Ah', "dclass": None, "icon": 'mdi:battery'},
    {"id": 'sensor.bestgo_installed_capacity', "name": 'BESTGO Installed Capacity', "unit": 'Ah', "dclass": None, "icon": 'mdi:battery'},
    {"id": 'sensor.bestgo_manufacturer', "name": 'BESTGO Manufacturer', "unit": None, "dclass": None, "icon": 'mdi:factory'},
    {"id": 'sensor.bestgo_battery_name', "name": 'BESTGO Battery Name', "unit": None, "dclass": None, "icon": 'mdi:tag'},
]

made = 0
for s in SENSORS:
    if hass.states.get(s["id"]) is not None:
        continue
    attributes = {"friendly_name": s["name"], "source": "solar_car_canbus", "icon": s["icon"]}
    if s["unit"]:
        attributes["unit_of_measurement"] = s["unit"]
    if s["dclass"]:
        attributes["device_class"] = s["dclass"]
    hass.states.set(s["id"], "unavailable", attributes)
    made = made + 1

logger.info("canbus bootstrap: created %d placeholder sensor(s)", made)
