#!/usr/bin/env python3
"""Vendor the shared solarcar_can package into the HA add-on folder.

Home Assistant builds local add-ons with the add-on directory as the Docker
build context, so the add-on cannot COPY files from outside it. This script
copies CANbus_data/solarcar_can/*.py into
ha_addons/solar-car-canbus/solarcar_can/, stamping each file with a
DO-NOT-EDIT header. Run it after any change to the package, then rebuild
the add-on on the Pi.

Usage:
    python sync_addon.py            # copy
    python sync_addon.py --check    # exit 1 if the vendored copy is stale
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE / "solarcar_can"
DST = HERE / "ha_addons" / "solar-car-canbus" / "solarcar_can"

HEADER = ("# GENERATED by CANbus_data/sync_addon.py -- DO NOT EDIT.\n"
          "# Edit CANbus_data/solarcar_can/ and re-run sync_addon.py.\n")


def vendored(src_file):
    return HEADER + src_file.read_text(encoding="utf-8")


def main():
    check = "--check" in sys.argv
    src_files = sorted(SRC.glob("*.py"))
    if not src_files:
        sys.exit(f"no package sources found in {SRC}")

    stale = []
    DST.mkdir(parents=True, exist_ok=True)
    for f in src_files:
        want = vendored(f)
        dst = DST / f.name
        if dst.exists() and dst.read_text(encoding="utf-8") == want:
            continue
        stale.append(f.name)
        if not check:
            dst.write_text(want, encoding="utf-8", newline="\n")

    # Remove vendored files whose source is gone.
    names = {f.name for f in src_files}
    for dst in DST.glob("*.py"):
        if dst.name not in names:
            stale.append(f"{dst.name} (removed)")
            if not check:
                dst.unlink()

    if check:
        if stale:
            print("vendored copy is stale:", ", ".join(stale))
            print("run:  python sync_addon.py")
            sys.exit(1)
        print("vendored copy is up to date")
    else:
        if stale:
            print("synced:", ", ".join(stale))
        else:
            print("already up to date")


if __name__ == "__main__":
    main()
