# GENERATED by CANbus_data/sync_addon.py -- DO NOT EDIT.
# Edit CANbus_data/solarcar_can/ and re-run sync_addon.py.
"""EZkontrol B48800 motor controller frame decoding (MCU-to-Meter protocol).

The controller broadcasts two J1939-style extended frames every 100 ms:

  * 0x180117EF -- bus voltage / bus current / phase current / speed
  * 0x180217EF -- temperatures / throttle / status bits / error bits / life

All values little-endian. See specs/ezkontrol_spec.txt and the
MCU-to-Meter v1.1 PDF for the field layout.
"""
import math
import random
import logging

log = logging.getLogger(__name__)

# --- frame IDs (extended 29-bit) ---------------------------------------------
MSG1_ID = 0x180117EF  # voltage, current, speed
MSG2_ID = 0x180217EF  # temps, status, errors

GEAR_NAMES = {0: "None", 1: "R", 2: "N", 3: "D1", 4: "D2", 5: "D3", 6: "S", 7: "P"}
OP_MODE_NAMES = {0: "Normal", 2: "Cruise", 3: "EBS", 4: "Hold"}

ERROR_BITS_BYTE4 = [
    "Overcurrent", "Overload", "Overvoltage", "Undervoltage",
    "Controller Overheat", "Motor Overheat", "Motor Stalled", "Motor Out of Phase",
]
ERROR_BITS_BYTE5 = [
    "Motor Sensor", "Motor AUX Sensor", "Encoder Misaligned", "Anti-Runaway",
    "Main Accelerator", "AUX Accelerator", "Pre-charge", "DC Contactor",
]
# Spec defines only bits 0-5 of byte 6; 6-7 are reserved.
ERROR_BITS_BYTE6 = [
    "Power Valve", "Current Sensor", "Auto-tune", "RS485", "CAN", "Software",
]


def parse_msg1(data):
    # Speed spec says 0.1 rpm/bit but +/-32000 rpm can't fit a uint16 at that
    # resolution. Empirically (motor at rest reads 0) it's 1 rpm/bit.
    return {
        "bus_voltage":   round(int.from_bytes(data[0:2], "little") * 0.1, 1),
        "bus_current":   round(int.from_bytes(data[2:4], "little") * 0.1 - 3200, 1),
        "phase_current": round(int.from_bytes(data[4:6], "little") * 0.1 - 3200, 1),
        "motor_speed":   int.from_bytes(data[6:8], "little") - 32000,
    }


def parse_msg2(data):
    sb = data[3]
    errors = []
    for bit, name in enumerate(ERROR_BITS_BYTE4):
        if data[4] & (1 << bit): errors.append(name)
    for bit, name in enumerate(ERROR_BITS_BYTE5):
        if data[5] & (1 << bit): errors.append(name)
    for bit, name in enumerate(ERROR_BITS_BYTE6):
        if data[6] & (1 << bit): errors.append(name)
    errors_str = ", ".join(errors) if errors else "None"
    if len(errors_str) > 250:                    # HA state values cap at 255
        errors_str = errors_str[:247] + "..."
    mode = (sb >> 4) & 0x07
    return {
        "controller_temp": data[0] - 40,
        "motor_temp":      data[1] - 40,
        "throttle":        data[2],
        "gear":            GEAR_NAMES.get(sb & 0x07, "Unknown"),
        "brake":           "On" if (sb >> 3) & 1 else "Off",
        "op_mode":         OP_MODE_NAMES.get(mode, f"?({mode})"),
        "dc_contactor":    "On" if (sb >> 7) & 1 else "Off",
        "errors":          errors_str,
        "error_count":     len(errors),
        "life":            data[7] >> 4,
    }


class EzkontrolDecoder:
    """decode() returns None for foreign frames, a field dict for EZkontrol's.

    Field names are the canonical set the HA sensors are built from
    (sensor.ezkontrol_<field>). Stateless; a class only for symmetry with
    BestgoDecoder so consumers treat all decoders alike.
    """

    def decode(self, arb_id, data):
        try:
            if arb_id == MSG1_ID and len(data) >= 8:
                return parse_msg1(data)
            if arb_id == MSG2_ID and len(data) >= 8:
                return parse_msg2(data)
            if arb_id in (MSG1_ID, MSG2_ID):
                return {}   # ours, but truncated -- claim it anyway
        except Exception:
            log.warning("malformed EZkontrol frame 0x%X: %s", arb_id,
                        bytes(data).hex(), exc_info=True)
            return {}
        return None


# --- HA sensor metadata (sensor.ezkontrol_<field>) ---------------------------
# Only fields listed here are pushed to HA; `life` (a rolling 4-bit counter)
# stays dashboard-only.
EZ_SENSORS = {
    "bus_voltage":     {"unit": "V",   "icon": "mdi:flash",             "device_class": "voltage"},
    "bus_current":     {"unit": "A",   "icon": "mdi:current-dc",        "device_class": "current"},
    "phase_current":   {"unit": "A",   "icon": "mdi:current-ac",        "device_class": "current"},
    "motor_speed":     {"unit": "rpm", "icon": "mdi:speedometer",       "device_class": None},
    "controller_temp": {"unit": "°C",  "icon": "mdi:thermometer",       "device_class": "temperature"},
    "motor_temp":      {"unit": "°C",  "icon": "mdi:thermometer-alert", "device_class": "temperature"},
    "throttle":        {"unit": "%",   "icon": "mdi:gauge",             "device_class": None},
    "gear":            {"unit": None,  "icon": "mdi:car-shift-pattern", "device_class": None},
    "brake":           {"unit": None,  "icon": "mdi:car-brake-alert",   "device_class": None},
    "op_mode":         {"unit": None,  "icon": "mdi:cog",               "device_class": None},
    "dc_contactor":    {"unit": None,  "icon": "mdi:electric-switch",   "device_class": None},
    "errors":          {"unit": None,  "icon": "mdi:alert-circle",      "device_class": None},
    "error_count":     {"unit": None,  "icon": "mdi:counter",           "device_class": None},
}


# --- dummy data (no hardware needed) -----------------------------------------
DUMMY_PERIOD = 0.1   # one simulated MCU broadcast cycle every 100 ms (as real)


def dummy_frames(t):
    """One simulated MCU broadcast cycle: (0x180117EF, 0x180217EF).

    `t` is elapsed seconds; drives a slow sinusoidal drive cycle.
    """
    rpm = max(0, int(1500 + 1350 * math.sin(t / 7.0)))
    throttle = min(100, max(0, int(rpm / 30)))
    ibus = round(2.0 + throttle * 0.85 + random.uniform(-1.5, 1.5), 1)
    iphase = round(ibus * 1.6, 1)
    v = round(72.0 - ibus * 0.03, 1)
    tctrl = int(32 + throttle * 0.12)
    tmot = int(38 + throttle * 0.18)
    brake = 1 if math.sin(t / 4.0) > 0.8 else 0
    sb = (4 & 7) | (brake << 3) | (1 << 7)        # gear D2, contactor ON
    life = int(t * 10) & 0x0F

    m1 = bytearray(8)
    m1[0:2] = int(round(v / 0.1)).to_bytes(2, "little")
    m1[2:4] = int(round((ibus + 3200) / 0.1)).to_bytes(2, "little")
    m1[4:6] = int(round((iphase + 3200) / 0.1)).to_bytes(2, "little")
    m1[6:8] = (rpm + 32000).to_bytes(2, "little")

    m2 = bytearray(8)
    m2[0] = tctrl + 40
    m2[1] = tmot + 40
    m2[2] = throttle
    m2[3] = sb
    m2[7] = (life & 0x0F) << 4
    return [(MSG1_ID, bytes(m1)), (MSG2_ID, bytes(m2))]


def dummy_fields():
    """One random snapshot of decoded fields (for the HA add-on's dummy mode)."""
    return {
        "bus_voltage":     round(random.uniform(48.0, 54.0), 1),
        "bus_current":     round(random.uniform(0.0, 25.0), 1),
        "phase_current":   round(random.uniform(0.0, 50.0), 1),
        "motor_speed":     random.randint(0, 3000),
        "controller_temp": random.randint(20, 45),
        "motor_temp":      random.randint(25, 55),
        "throttle":        random.randint(0, 100),
        "gear":            random.choice(["D1", "D2", "D3", "N"]),
        "brake":           random.choice(["Off", "Off", "Off", "On"]),
        "op_mode":         "Normal",
        "dc_contactor":    "On",
        "errors":          "None",
        "error_count":     0,
        "life":            random.randint(0, 15),
    }
