#!/usr/bin/env python3
"""Generate the HA python_script that bootstraps the CAN sensor entities.

The CAN reader add-on creates sensor.ezkontrol_* / sensor.bestgo_* by POSTing
to Home Assistant's REST /api/states, and only once a fresh frame has populated
each field -- and REST-created states don't survive an HA restart. So before
the bus comes up (or right after a restart) those entities don't exist and the
dashboard shows "entity not found", with nothing to browse in history.

This emits a python_script that, on the homeassistant.start event (wired up by
ha/packages/canbus_bootstrap.yaml), creates each known sensor as "unavailable"
IF it doesn't already exist -- so the cards render and history stays browsable
while the bus is silent, without ever clobbering a live value the add-on has
already pushed.

The sensor list is derived from EZ_SENSORS / BG_SENSORS so it stays in sync
with the decoders. Re-run after changing those tables:

    python CANbus_data/tools/gen_ha_bootstrap.py
"""
import os
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # CANbus_data/
sys.path.insert(0, HERE)  # so `solarcar_can` imports from the source package

from solarcar_can.ezkontrol import EZ_SENSORS   # noqa: E402
from solarcar_can.bestgo import BG_SENSORS       # noqa: E402

DEVICES = [("EZkontrol", "ezkontrol", EZ_SENSORS),
           ("BESTGO", "bestgo", BG_SENSORS)]

OUT = os.path.join(HERE, "ha", "python_scripts", "bootstrap_canbus_entities.py")


def rows():
    for dev_name, prefix, table in DEVICES:
        for key, cfg in table.items():
            yield (
                f"sensor.{prefix}_{key}",
                f"{dev_name} " + key.replace("_", " ").title(),
                cfg.get("unit"),
                cfg.get("device_class"),
                cfg.get("icon", "mdi:information"),
            )


HEADER = '''\
# AUTO-GENERATED by CANbus_data/tools/gen_ha_bootstrap.py -- do not edit by hand.
# Regenerate after changing EZ_SENSORS / BG_SENSORS.
#
# Home Assistant python_script (runs in the restricted python_script sandbox).
# Creates each CAN sensor as "unavailable" if it does not already exist, so the
# dashboard shows the entity (not "entity not found") and history stays
# browsable before the CAN reader add-on has live data. Triggered on the
# homeassistant.start event by the automation in packages/canbus_bootstrap.yaml.
# The existence check means it never clobbers a live value the add-on pushed.

SENSORS = [
'''

BODY = '''\
]

made = 0
for s in SENSORS:
    if hass.states.get(s["id"]) is not None:
        continue
    attributes = {"friendly_name": s["name"], "source": "solar_car_canbus", "icon": s["icon"]}
    if s["unit"]:
        attributes["unit_of_measurement"] = s["unit"]
    if s["dclass"]:
        attributes["device_class"] = s["dclass"]
    hass.states.set(s["id"], "unavailable", attributes)
    made = made + 1

logger.info("canbus bootstrap: created %d placeholder sensor(s)", made)
'''


def main():
    parts = [HEADER]
    n = 0
    for eid, name, unit, dclass, icon in rows():
        parts.append(
            f'    {{"id": {eid!r}, "name": {name!r}, '
            f'"unit": {unit!r}, "dclass": {dclass!r}, "icon": {icon!r}}},\n'
        )
        n += 1
    parts.append(BODY)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("".join(parts))
    print(f"wrote {OUT} ({n} sensors)")


if __name__ == "__main__":
    main()
